version: '3.9'
services:
  mcp:
    build:
      context: .
      dockerfile: packages/traide-mcp/Dockerfile
    environment:
      - PORT=62007
      - MCP_CORS_ORIGINS=*
    ports:
      - "62007:62007"
  ui:
    build:
      context: .
      dockerfile: apps/traide-ui/Dockerfile
    environment:
      - NEXT_PUBLIC_MCP_BASE_URL=http://mcp:62007
      - PORT=62008
    ports:
      - "62008:62008"
    depends_on:
      - mcp
